### ISSUE TITLE
Adding locales to static routes causes exception

### ISSUE THREAD

**Issue by sweoggy** [stefandoorn/sitemap-plugin#23]
Config.yml:
```
sitemap:
    providers:
        taxons: false
    static_routes:
        - { route: sylius_shop_homepage }
        - { route: sylius_shop_login, locales: ["sv", "en"] }
```

> InvalidConfigurationException
> Unrecognized options "0, 1" under "sylius_sitemap.static_routes.1.locales"

Probably related https://github.com/Sylius/Sylius/issues/8187
