### ISSUE TITLE
Example of how to use parameters

### ISSUE THREAD

**Issue by othbert** [stefandoorn/sitemap-plugin#39]
Hi, thanks for the plugin, all looks great except can't quite work out how to use the parameters on static routes effectively.

We have, for example, a single route for static pages that takes a parameter "page" and accepts several strings in order to generate some static content pages... imagine "/terms , /about , /info", those kinds of things. Could you please give some pointers on how would it be possible to specify in the configuration that these pages should be added to the sitemap? 
The closest I've got to it working with the configuration is something like
```
parameters:
    - ['page', ['terms', 'about', 'info']]
```

But this gives:
```
InvalidConfigurationException
Unrecognized options "0, 1" under "sylius_sitemap.static_routes.0.parameters.0"
```

Thanks!

**Comment by stefandoorn** [comment]
Hi @othbert. I think this is similar to #34. Recently a PR was submitted (#38) to resolve this issue, but I haven't been able to test it yet. Could you test that PR to see if it resolves your issue?

**Comment by othbert** [comment]
Hi there! Yup, sorry, I was going to submit as a comment on that, but thought twice about it.

I did test that PR and I think it's pointed me in a better direction... However, I'd love to see an example of the intended setup of parameters for a route, as I think I may be mistaking how this should work.

Anyway, I'm now supplying the same route alias several times, changing the page parameter each time, this seems to work better along with the fix in the PR, however I end up with duplicated entries in the resultant sitemap.

configuration:
```
    static_routes:
        -
            route: static_content_page
            parameters:
                page: 'terms'
            locales: ['en','de','es']
        -
            route: static_content_page
            parameters:
                page: 'about'
            locales: ['en','de','es']
        -
            route: static_content_page
            parameters:
                page: 'info'
            locales: ['en','de','es']
```

Gives me the entries for these routes, but after it's listed them all, it gives me the output again so it ends up with .../en/terms etc. following .../es/info
